name: CI
on: [push, pull_request]

jobs:
  go-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.1'
      - run:
          go build main.go
      - run: |
          go fmt ./...
          git diff --exit-code
